In [8]:
import numpy as np
import pandas as pd
import seaborn as sns
sns.set()
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.ensemble import RandomForestRegressor
import warnings
warnings.filterwarnings('ignore')

In [9]:
train_data = pd.read_csv("/content/train.csv", encoding_errors = "ignore")
test_data = pd.read_csv("/content/test.csv", encoding_errors = "ignore")
sample_data = pd.read_csv("/content/sample_submission.csv", encoding_errors = "ignore")
store_data = pd.read_csv("/content/store.csv", encoding_errors = "ignore")

In [10]:
train_data

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
0,1,5,2015-07-31,5263,555,1,1,0,1
1,2,5,2015-07-31,6064,625,1,1,0,1
2,3,5,2015-07-31,8314,821,1,1,0,1
3,4,5,2015-07-31,13995,1498,1,1,0,1
4,5,5,2015-07-31,4822,559,1,1,0,1
...,...,...,...,...,...,...,...,...,...
1017204,1111,2,2013-01-01,0,0,0,0,a,1
1017205,1112,2,2013-01-01,0,0,0,0,a,1
1017206,1113,2,2013-01-01,0,0,0,0,a,1
1017207,1114,2,2013-01-01,0,0,0,0,a,1
1017208,1115,2,2013-01-01,0,0,0,0,a,1

In [11]:
test_data

,Id,Store,DayOfWeek,Date,Open,Promo,StateHoliday,SchoolHoliday
0,1,1,4,2015-09-17,1.0,1,0,0
1,2,3,4,2015-09-17,1.0,1,0,0
2,3,7,4,2015-09-17,1.0,1,0,0
3,4,8,4,2015-09-17,1.0,1,0,0
4,5,9,4,2015-09-17,1.0,1,0,0
...,...,...,...,...,...,...,...,...
41083,41084,1111,6,2015-08-01,1.0,0,0,0
41084,41085,1112,6,2015-08-01,1.0,0,0,0
41085,41086,1113,6,2015-08-01,1.0,0,0,0
41086,41087,1114,6,2015-08-01,1.0,0,0,0
41087,41088,1115,6,2015-08-01,1.0,0,0,1

In [12]:
store_data

,Store,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1,2,a,a,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
2,3,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
3,4,c,c,620.0,9.0,2009.0,0,NaN,NaN,NaN
4,5,a,a,29910.0,4.0,2015.0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
1110,1111,a,a,1900.0,6.0,2014.0,1,31.0,2013.0,"Jan,Apr,Jul,Oct"
1111,1112,c,c,1880.0,4.0,2006.0,0,NaN,NaN,NaN
1112,1113,a,c,9260.0,NaN,NaN,0,NaN,NaN,NaN
1113,1114,a,c,870.0,NaN,NaN,0,NaN,NaN,NaN
1114,1115,d,c,5350.0,NaN,NaN,1,22.0,2012.0,"Mar,Jun,Sept,Dec"

In [13]:
sample_data

          Id  Sales
0          1      0
1          2      0
2          3      0
3          4      0
4          5      0
...      ...    ...
41083  41084      0
41084  41085      0
41085  41086      0
41086  41087      0
41087  41088      0

[41088 rows x 2 columns]

In [14]:
train_data.shape

(1017209, 9)

In [15]:
sample_data.shape

(41088, 2)

In [16]:
store_data.shape

(1115, 10)

In [17]:
test_data.shape

(41088, 8)

Task 2 - Prediction of store sales

In [18]:
train_data.head()

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
0,1,5,2015-07-31,5263,555,1,1,0,1
1,2,5,2015-07-31,6064,625,1,1,0,1
2,3,5,2015-07-31,8314,821,1,1,0,1
3,4,5,2015-07-31,13995,1498,1,1,0,1
4,5,5,2015-07-31,4822,559,1,1,0,1

In [19]:
test_data.head()

   Id  Store  DayOfWeek        Date  Open  Promo StateHoliday  SchoolHoliday
0   1      1          4  2015-09-17   1.0      1            0              0
1   2      3          4  2015-09-17   1.0      1            0              0
2   3      7          4  2015-09-17   1.0      1            0              0
3   4      8          4  2015-09-17   1.0      1            0              0
4   5      9          4  2015-09-17   1.0      1            0              0

In [20]:
store_data.head()

,Store,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1,2,a,a,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
2,3,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
3,4,c,c,620.0,9.0,2009.0,0,NaN,NaN,NaN
4,5,a,a,29910.0,4.0,2015.0,0,NaN,NaN,NaN

In [21]:
sample_data.head()

   Id  Sales
0   1      0
1   2      0
2   3      0
3   4      0
4   5      0

In [22]:
test_data.columns

Index(['Id', 'Store', 'DayOfWeek', 'Date', 'Open', 'Promo', 'StateHoliday',
       'SchoolHoliday'],
      dtype='object')

In [23]:
train_data.columns

Index(['Store', 'DayOfWeek', 'Date', 'Sales', 'Customers', 'Open', 'Promo',
       'StateHoliday', 'SchoolHoliday'],
      dtype='object')

In [24]:
sample_data.columns

Index(['Id', 'Sales'], dtype='object')

In [25]:
store_data.columns

Index(['Store', 'StoreType', 'Assortment', 'CompetitionDistance',
       'CompetitionOpenSinceMonth', 'CompetitionOpenSinceYear', 'Promo2',
       'Promo2SinceWeek', 'Promo2SinceYear', 'PromoInterval'],
      dtype='object')

Merge Data

store data merging with train data

In [26]:
common_key = 'Store'

In [27]:
train_merged_data = pd.merge(train_data, store_data, on=common_key, how='left')

In [28]:
train_merged_data

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,5,2015-07-31,5263,555,1,1,0,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1,2,5,2015-07-31,6064,625,1,1,0,1,a,a,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
2,3,5,2015-07-31,8314,821,1,1,0,1,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
3,4,5,2015-07-31,13995,1498,1,1,0,1,c,c,620.0,9.0,2009.0,0,NaN,NaN,NaN
4,5,5,2015-07-31,4822,559,1,1,0,1,a,a,29910.0,4.0,2015.0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1017204,1111,2,2013-01-01,0,0,0,0,a,1,a,a,1900.0,6.0,2014.0,1,31.0,2013.0,"Jan,Apr,Jul,Oct"
1017205,1112,2,2013-01-01,0,0,0,0,a,1,c,c,1880.0,4.0,2006.0,0,NaN,NaN,NaN
1017206,1113,2,2013-01-01,0,0,0,0,a,1,a,c,9260.0,NaN,NaN,0,NaN,NaN,NaN
1017207,1114,2,2013-01-01,0,0,0,0,a,1,a,c,870.0,NaN,NaN,0,NaN,NaN,NaN
1017208,1115,2,2013-01-01,0,0,0,0,a,1,d,c,5350.0,NaN,NaN,1,22.0,2012.0,"Mar,Jun,Sept,Dec"

In [29]:
train_merged_data.head()

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,5,2015-07-31,5263,555,1,1,0,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1,2,5,2015-07-31,6064,625,1,1,0,1,a,a,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
2,3,5,2015-07-31,8314,821,1,1,0,1,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
3,4,5,2015-07-31,13995,1498,1,1,0,1,c,c,620.0,9.0,2009.0,0,NaN,NaN,NaN
4,5,5,2015-07-31,4822,559,1,1,0,1,a,a,29910.0,4.0,2015.0,0,NaN,NaN,NaN

In [30]:
train_merged_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1017209 entries, 0 to 1017208
Data columns (total 18 columns):
 #   Column                     Non-Null Count    Dtype
---  ------                     --------------    -----
 0   Store                      1017209 non-null  int64
 1   DayOfWeek                  1017209 non-null  int64
 2   Date                       1017209 non-null  object
 3   Sales                      1017209 non-null  int64
 4   Customers                  1017209 non-null  int64
 5   Open                       1017209 non-null  int64
 6   Promo                      1017209 non-null  int64
 7   StateHoliday               1017209 non-null  object
 8   SchoolHoliday              1017209 non-null  int64
 9   StoreType                  1017209 non-null  object
 10  Assortment                 1017209 non-null  object
 11  CompetitionDistance        1014567 non-null  float64
 12  CompetitionOpenSinceMonth  693861 non-null   float64
 13  CompetitionOpenSinceYear   693861 non-null   float64
 14  Promo2                     1017209 non-null  int64
 15  Promo2SinceWeek            509178 non-null   float64
 16  Promo2SinceYear            509178 non-null   float64
 17  PromoInterval              509178 non-null   object
dtypes: float64(5), int64(8), object(5)
memory usage: 147.5+ MB

In [31]:
train_merged_data.columns

Index(['Store', 'DayOfWeek', 'Date', 'Sales', 'Customers', 'Open', 'Promo',
       'StateHoliday', 'SchoolHoliday', 'StoreType', 'Assortment',
       'CompetitionDistance', 'CompetitionOpenSinceMonth',
       'CompetitionOpenSinceYear', 'Promo2', 'Promo2SinceWeek',
       'Promo2SinceYear', 'PromoInterval'],
      dtype='object')

In [32]:
train_merged_data.describe()

,Store,DayOfWeek,Sales,Customers,Open,Promo,SchoolHoliday,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear
count,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06,1.014567e+06,693861.000000,693861.000000,1.017209e+06,509178.000000,509178.000000
mean,5.584297e+02,3.998341e+00,5.773819e+03,6.331459e+02,8.301067e-01,3.815145e-01,1.786467e-01,5.430086e+03,7.222866,2008.690228,5.005638e-01,23.269093,2011.752774
std,3.219087e+02,1.997391e+00,3.849926e+03,4.644117e+02,3.755392e-01,4.857586e-01,3.830564e-01,7.715324e+03,3.211832,5.992644,4.999999e-01,14.095973,1.662870
min,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.000000e+01,1.000000,1900.000000,0.000000e+00,1.000000,2009.000000
25%,2.800000e+02,2.000000e+00,3.727000e+03,4.050000e+02,1.000000e+00,0.000000e+00,0.000000e+00,7.100000e+02,4.000000,2006.000000,0.000000e+00,13.000000,2011.000000
50%,5.580000e+02,4.000000e+00,5.744000e+03,6.090000e+02,1.000000e+00,0.000000e+00,0.000000e+00,2.330000e+03,8.000000,2010.000000,1.000000e+00,22.000000,2012.000000
75%,8.380000e+02,6.000000e+00,7.856000e+03,8.370000e+02,1.000000e+00,1.000000e+00,0.000000e+00,6.890000e+03,10.000000,2013.000000,1.000000e+00,37.000000,2013.000000
max,1.115000e+03,7.000000e+00,4.155100e+04,7.388000e+03,1.000000e+00,1.000000e+00,1.000000e+00,7.586000e+04,12.000000,2015.000000,1.000000e+00,50.000000,2015.000000

In [33]:
train_merged_data.isnull().sum()

Store                             0
DayOfWeek                         0
Date                              0
Sales                             0
Customers                         0
Open                              0
Promo                             0
StateHoliday                      0
SchoolHoliday                     0
StoreType                         0
Assortment                        0
CompetitionDistance            2642
CompetitionOpenSinceMonth    323348
CompetitionOpenSinceYear     323348
Promo2                            0
Promo2SinceWeek              508031
Promo2SinceYear              508031
PromoInterval                508031
dtype: int64

Store data merging with test data

In [34]:
test_merged_data= pd.merge(test_data, store_data, on=common_key, how='left')

In [35]:
test_merged_data

,Id,Store,DayOfWeek,Date,Open,Promo,StateHoliday,SchoolHoliday,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,1,4,2015-09-17,1.0,1,0,0,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1,2,3,4,2015-09-17,1.0,1,0,0,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
2,3,7,4,2015-09-17,1.0,1,0,0,a,c,24000.0,4.0,2013.0,0,NaN,NaN,NaN
3,4,8,4,2015-09-17,1.0,1,0,0,a,a,7520.0,10.0,2014.0,0,NaN,NaN,NaN
4,5,9,4,2015-09-17,1.0,1,0,0,a,c,2030.0,8.0,2000.0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41083,41084,1111,6,2015-08-01,1.0,0,0,0,a,a,1900.0,6.0,2014.0,1,31.0,2013.0,"Jan,Apr,Jul,Oct"
41084,41085,1112,6,2015-08-01,1.0,0,0,0,c,c,1880.0,4.0,2006.0,0,NaN,NaN,NaN
41085,41086,1113,6,2015-08-01,1.0,0,0,0,a,c,9260.0,NaN,NaN,0,NaN,NaN,NaN
41086,41087,1114,6,2015-08-01,1.0,0,0,0,a,c,870.0,NaN,NaN,0,NaN,NaN,NaN
41087,41088,1115,6,2015-08-01,1.0,0,0,1,d,c,5350.0,NaN,NaN,1,22.0,2012.0,"Mar,Jun,Sept,Dec"

In [36]:
test_merged_data.head()

,Id,Store,DayOfWeek,Date,Open,Promo,StateHoliday,SchoolHoliday,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,1,4,2015-09-17,1.0,1,0,0,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1,2,3,4,2015-09-17,1.0,1,0,0,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
2,3,7,4,2015-09-17,1.0,1,0,0,a,c,24000.0,4.0,2013.0,0,NaN,NaN,NaN
3,4,8,4,2015-09-17,1.0,1,0,0,a,a,7520.0,10.0,2014.0,0,NaN,NaN,NaN
4,5,9,4,2015-09-17,1.0,1,0,0,a,c,2030.0,8.0,2000.0,0,NaN,NaN,NaN

In [37]:
test_merged_data.columns

Index(['Id', 'Store', 'DayOfWeek', 'Date', 'Open', 'Promo', 'StateHoliday',
       'SchoolHoliday', 'StoreType', 'Assortment', 'CompetitionDistance',
       'CompetitionOpenSinceMonth', 'CompetitionOpenSinceYear', 'Promo2',
       'Promo2SinceWeek', 'Promo2SinceYear', 'PromoInterval'],
      dtype='object')

In [38]:
test_merged_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 41088 entries, 0 to 41087
Data columns (total 17 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Id                         41088 non-null  int64
 1   Store                      41088 non-null  int64
 2   DayOfWeek                  41088 non-null  int64
 3   Date                       41088 non-null  object
 4   Open                       41077 non-null  float64
 5   Promo                      41088 non-null  int64
 6   StateHoliday               41088 non-null  object
 7   SchoolHoliday              41088 non-null  int64
 8   StoreType                  41088 non-null  object
 9   Assortment                 41088 non-null  object
 10  CompetitionDistance        40992 non-null  float64
 11  CompetitionOpenSinceMonth  25872 non-null  float64
 12  CompetitionOpenSinceYear   25872 non-null  float64
 13  Promo2                     41088 non-null  int64
 14  Promo2SinceWeek            23856 non-null  float64
 15  Promo2SinceYear            23856 non-null  float64
 16  PromoInterval              23856 non-null  object
dtypes: float64(6), int64(6), object(5)
memory usage: 5.6+ MB

In [39]:
test_merged_data.describe()

,Id,Store,DayOfWeek,Open,Promo,SchoolHoliday,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear
count,41088.000000,41088.000000,41088.000000,41077.000000,41088.000000,41088.000000,40992.000000,25872.000000,25872.000000,41088.000000,23856.000000,23856.000000
mean,20544.500000,555.899533,3.979167,0.854322,0.395833,0.443487,5088.583138,7.035250,2008.641929,0.580607,24.426559,2011.820926
std,11861.228267,320.274496,2.015481,0.352787,0.489035,0.496802,7225.487467,3.143015,6.862400,0.493466,14.161312,1.692166
min,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,20.000000,1.000000,1900.000000,0.000000,1.000000,2009.000000
25%,10272.750000,279.750000,2.000000,1.000000,0.000000,0.000000,720.000000,4.000000,2006.000000,0.000000,13.000000,2011.000000
50%,20544.500000,553.500000,4.000000,1.000000,0.000000,0.000000,2425.000000,7.000000,2010.000000,1.000000,22.000000,2012.000000
75%,30816.250000,832.250000,6.000000,1.000000,1.000000,1.000000,6480.000000,9.000000,2012.000000,1.000000,37.000000,2013.000000
max,41088.000000,1115.000000,7.000000,1.000000,1.000000,1.000000,75860.000000,12.000000,2015.000000,1.000000,49.000000,2015.000000

In [40]:
test_merged_data.isnull().sum()

Id                               0
Store                            0
DayOfWeek                        0
Date                             0
Open                            11
Promo                            0
StateHoliday                     0
SchoolHoliday                    0
StoreType                        0
Assortment                       0
CompetitionDistance             96
CompetitionOpenSinceMonth    15216
CompetitionOpenSinceYear     15216
Promo2                           0
Promo2SinceWeek              17232
Promo2SinceYear              17232
PromoInterval                17232
dtype: int64

In [41]:
train_merged_data['Date'] = pd.to_datetime(train_merged_data['Date'])
test_merged_data['Date'] = pd.to_datetime(test_merged_data['Date'])

In [42]:
train_merged_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1017209 entries, 0 to 1017208
Data columns (total 18 columns):
 #   Column                     Non-Null Count    Dtype
---  ------                     --------------    -----
 0   Store                      1017209 non-null  int64
 1   DayOfWeek                  1017209 non-null  int64
 2   Date                       1017209 non-null  datetime64[ns]
 3   Sales                      1017209 non-null  int64
 4   Customers                  1017209 non-null  int64
 5   Open                       1017209 non-null  int64
 6   Promo                      1017209 non-null  int64
 7   StateHoliday               1017209 non-null  object
 8   SchoolHoliday              1017209 non-null  int64
 9   StoreType                  1017209 non-null  object
 10  Assortment                 1017209 non-null  object
 11  CompetitionDistance        1014567 non-null  float64
 12  CompetitionOpenSinceMonth  693861 non-null   float64
 13  CompetitionOpenSinceYear   693861 non-null   float64
 14  Promo2                     1017209 non-null  int64
 15  Promo2SinceWeek            509178 non-null   float64
 16  Promo2SinceYear            509178 non-null   float64
 17  PromoInterval              509178 non-null   object
dtypes: datetime64[ns](1), float64(5), int64(8), object(4)
memory usage: 147.5+ MB

In [43]:
test_merged_data.columns

Index(['Id', 'Store', 'DayOfWeek', 'Date', 'Open', 'Promo', 'StateHoliday',
       'SchoolHoliday', 'StoreType', 'Assortment', 'CompetitionDistance',
       'CompetitionOpenSinceMonth', 'CompetitionOpenSinceYear', 'Promo2',
       'Promo2SinceWeek', 'Promo2SinceYear', 'PromoInterval'],
      dtype='object')

train data and test data describe

In [44]:
train_merged_data.describe()

,Store,DayOfWeek,Sales,Customers,Open,Promo,SchoolHoliday,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear
count,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06,1.017209e+06,1.014567e+06,693861.000000,693861.000000,1.017209e+06,509178.000000,509178.000000
mean,5.584297e+02,3.998341e+00,5.773819e+03,6.331459e+02,8.301067e-01,3.815145e-01,1.786467e-01,5.430086e+03,7.222866,2008.690228,5.005638e-01,23.269093,2011.752774
std,3.219087e+02,1.997391e+00,3.849926e+03,4.644117e+02,3.755392e-01,4.857586e-01,3.830564e-01,7.715324e+03,3.211832,5.992644,4.999999e-01,14.095973,1.662870
min,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.000000e+01,1.000000,1900.000000,0.000000e+00,1.000000,2009.000000
25%,2.800000e+02,2.000000e+00,3.727000e+03,4.050000e+02,1.000000e+00,0.000000e+00,0.000000e+00,7.100000e+02,4.000000,2006.000000,0.000000e+00,13.000000,2011.000000
50%,5.580000e+02,4.000000e+00,5.744000e+03,6.090000e+02,1.000000e+00,0.000000e+00,0.000000e+00,2.330000e+03,8.000000,2010.000000,1.000000e+00,22.000000,2012.000000
75%,8.380000e+02,6.000000e+00,7.856000e+03,8.370000e+02,1.000000e+00,1.000000e+00,0.000000e+00,6.890000e+03,10.000000,2013.000000,1.000000e+00,37.000000,2013.000000
max,1.115000e+03,7.000000e+00,4.155100e+04,7.388000e+03,1.000000e+00,1.000000e+00,1.000000e+00,7.586000e+04,12.000000,2015.000000,1.000000e+00,50.000000,2015.000000

In [45]:
test_merged_data.describe()

,Id,Store,DayOfWeek,Open,Promo,SchoolHoliday,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear
count,41088.000000,41088.000000,41088.000000,41077.000000,41088.000000,41088.000000,40992.000000,25872.000000,25872.000000,41088.000000,23856.000000,23856.000000
mean,20544.500000,555.899533,3.979167,0.854322,0.395833,0.443487,5088.583138,7.035250,2008.641929,0.580607,24.426559,2011.820926
std,11861.228267,320.274496,2.015481,0.352787,0.489035,0.496802,7225.487467,3.143015,6.862400,0.493466,14.161312,1.692166
min,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,20.000000,1.000000,1900.000000,0.000000,1.000000,2009.000000
25%,10272.750000,279.750000,2.000000,1.000000,0.000000,0.000000,720.000000,4.000000,2006.000000,0.000000,13.000000,2011.000000
50%,20544.500000,553.500000,4.000000,1.000000,0.000000,0.000000,2425.000000,7.000000,2010.000000,1.000000,22.000000,2012.000000
75%,30816.250000,832.250000,6.000000,1.000000,1.000000,1.000000,6480.000000,9.000000,2012.000000,1.000000,37.000000,2013.000000
max,41088.000000,1115.000000,7.000000,1.000000,1.000000,1.000000,75860.000000,12.000000,2015.000000,1.000000,49.000000,2015.000000

2.1 Preprocessing

It is important to process the data into a format where it can be fed to a machine learning model. This typically means converting all non-numeric columns to numeric, handling NaN values and generating new features from already existing features. In our case, you have a few datetime columns to preprocess. you can extract the following from them:

weekdays

weekends

number of days to holidays

Number of days after holiday

Beginning of month, mid month and ending of month

(think of more features to extract), extra marks for it As a final thing, you have to scale the data
This helps with predictions especially when using machine learning algorithms that use Euclidean distances.
  you can use the standard scaler in sklearn for this

In [46]:
train_merged_data.columns

Index(['Store', 'DayOfWeek', 'Date', 'Sales', 'Customers', 'Open', 'Promo',
       'StateHoliday', 'SchoolHoliday', 'StoreType', 'Assortment',
       'CompetitionDistance', 'CompetitionOpenSinceMonth',
       'CompetitionOpenSinceYear', 'Promo2', 'Promo2SinceWeek',
       'Promo2SinceYear', 'PromoInterval'],
      dtype='object')

In [47]:
test_merged_data.columns

Index(['Id', 'Store', 'DayOfWeek', 'Date', 'Open', 'Promo', 'StateHoliday',
       'SchoolHoliday', 'StoreType', 'Assortment', 'CompetitionDistance',
       'CompetitionOpenSinceMonth', 'CompetitionOpenSinceYear', 'Promo2',
       'Promo2SinceWeek', 'Promo2SinceYear', 'PromoInterval'],
      dtype='object')

In [48]:
# Extract features from the 'Date' column for both train and test data
# Extract Year
train_merged_data['Year'] = train_merged_data['Date'].dt.year
test_merged_data['Year'] = test_merged_data['Date'].dt.year

In [49]:
train_merged_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1017209 entries, 0 to 1017208
Data columns (total 19 columns):
 #   Column                     Non-Null Count    Dtype
---  ------                     --------------    -----
 0   Store                      1017209 non-null  int64
 1   DayOfWeek                  1017209 non-null  int64
 2   Date                       1017209 non-null  datetime64[ns]
 3   Sales                      1017209 non-null  int64
 4   Customers                  1017209 non-null  int64
 5   Open                       1017209 non-null  int64
 6   Promo                      1017209 non-null  int64
 7   StateHoliday               1017209 non-null  object
 8   SchoolHoliday              1017209 non-null  int64
 9   StoreType                  1017209 non-null  object
 10  Assortment                 1017209 non-null  object
 11  CompetitionDistance        1014567 non-null  float64
 12  CompetitionOpenSinceMonth  693861 non-null   float64
 13  CompetitionOpenSinceYear   693861 non-null   float64
 14  Promo2                     1017209 non-null  int64
 15  Promo2SinceWeek            509178 non-null   float64
 16  Promo2SinceYear            509178 non-null   float64
 17  PromoInterval              509178 non-null   object
 18  Year                       1017209 non-null  int64
dtypes: datetime64[ns](1), float64(5), int64(9), object(4)
memory usage: 155.2+ MB

In [50]:
test_merged_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 41088 entries, 0 to 41087
Data columns (total 18 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Id                         41088 non-null  int64
 1   Store                      41088 non-null  int64
 2   DayOfWeek                  41088 non-null  int64
 3   Date                       41088 non-null  datetime64[ns]
 4   Open                       41077 non-null  float64
 5   Promo                      41088 non-null  int64
 6   StateHoliday               41088 non-null  object
 7   SchoolHoliday              41088 non-null  int64
 8   StoreType                  41088 non-null  object
 9   Assortment                 41088 non-null  object
 10  CompetitionDistance        40992 non-null  float64
 11  CompetitionOpenSinceMonth  25872 non-null  float64
 12  CompetitionOpenSinceYear   25872 non-null  float64
 13  Promo2                     41088 non-null  int64
 14  Promo2SinceWeek            23856 non-null  float64
 15  Promo2SinceYear            23856 non-null  float64
 16  PromoInterval              23856 non-null  object
 17  Year                       41088 non-null  int64
dtypes: datetime64[ns](1), float64(6), int64(7), object(4)
memory usage: 6.0+ MB

In [51]:
# Extract Month
train_merged_data['Month'] = train_merged_data['Date'].dt.month
test_merged_data['Month'] = test_merged_data['Date'].dt.month

In [52]:
train_merged_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1017209 entries, 0 to 1017208
Data columns (total 20 columns):
 #   Column                     Non-Null Count    Dtype
---  ------                     --------------    -----
 0   Store                      1017209 non-null  int64
 1   DayOfWeek                  1017209 non-null  int64
 2   Date                       1017209 non-null  datetime64[ns]
 3   Sales                      1017209 non-null  int64
 4   Customers                  1017209 non-null  int64
 5   Open                       1017209 non-null  int64
 6   Promo                      1017209 non-null  int64
 7   StateHoliday               1017209 non-null  object
 8   SchoolHoliday              1017209 non-null  int64
 9   StoreType                  1017209 non-null  object
 10  Assortment                 1017209 non-null  object
 11  CompetitionDistance        1014567 non-null  float64
 12  CompetitionOpenSinceMonth  693861 non-null   float64
 13  CompetitionOpenSinceYear   693861 non-null   float64
 14  Promo2                     1017209 non-null  int64
 15  Promo2SinceWeek            509178 non-null   float64
 16  Promo2SinceYear            509178 non-null   float64
 17  PromoInterval              509178 non-null   object
 18  Year                       1017209 non-null  int64
 19  Month                      1017209 non-null  int64
dtypes: datetime64[ns](1), float64(5), int64(10), object(4)
memory usage: 163.0+ MB

In [53]:
test_merged_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 41088 entries, 0 to 41087
Data columns (total 19 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Id                         41088 non-null  int64
 1   Store                      41088 non-null  int64
 2   DayOfWeek                  41088 non-null  int64
 3   Date                       41088 non-null  datetime64[ns]
 4   Open                       41077 non-null  float64
 5   Promo                      41088 non-null  int64
 6   StateHoliday               41088 non-null  object
 7   SchoolHoliday              41088 non-null  int64
 8   StoreType                  41088 non-null  object
 9   Assortment                 41088 non-null  object
 10  CompetitionDistance        40992 non-null  float64
 11  CompetitionOpenSinceMonth  25872 non-null  float64
 12  CompetitionOpenSinceYear   25872 non-null  float64
 13  Promo2                     41088 non-null  int64
 14  Promo2SinceWeek            23856 non-null  float64
 15  Promo2SinceYear            23856 non-null  float64
 16  PromoInterval              23856 non-null  object
 17  Year                       41088 non-null  int64
 18  Month                      41088 non-null  int64
dtypes: datetime64[ns](1), float64(6), int64(8), object(4)
memory usage: 6.3+ MB

In [54]:
# Extract Day
train_merged_data['weekDay'] = train_merged_data['Date'].dt.day
test_merged_data['weekDay'] = test_merged_data['Date'].dt.day

In [55]:
# Create a feature for Weekday (1=Weekday, 0=Weekend)
train_merged_data['IsWeekday'] = (train_merged_data['DayOfWeek'] < 5).astype(int)
test_merged_data['IsWeekday'] = (test_merged_data['DayOfWeek'] < 5).astype(int)

In [56]:
train_merged_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1017209 entries, 0 to 1017208
Data columns (total 22 columns):
 #   Column                     Non-Null Count    Dtype
---  ------                     --------------    -----
 0   Store                      1017209 non-null  int64
 1   DayOfWeek                  1017209 non-null  int64
 2   Date                       1017209 non-null  datetime64[ns]
 3   Sales                      1017209 non-null  int64
 4   Customers                  1017209 non-null  int64
 5   Open                       1017209 non-null  int64
 6   Promo                      1017209 non-null  int64
 7   StateHoliday               1017209 non-null  object
 8   SchoolHoliday              1017209 non-null  int64
 9   StoreType                  1017209 non-null  object
 10  Assortment                 1017209 non-null  object
 11  CompetitionDistance        1014567 non-null  float64
 12  CompetitionOpenSinceMonth  693861 non-null   float64
 13  CompetitionOpenSinceYear   693861 non-null   float64
 14  Promo2                     1017209 non-null  int64
 15  Promo2SinceWeek            509178 non-null   float64
 16  Promo2SinceYear            509178 non-null   float64
 17  PromoInterval              509178 non-null   object
 18  Year                       1017209 non-null  int64
 19  Month                      1017209 non-null  int64
 20  weekDay                    1017209 non-null  int64
 21  IsWeekday                  1017209 non-null  int64
dtypes: datetime64[ns](1), float64(5), int64(12), object(4)
memory usage: 178.5+ MB

In [57]:
test_merged_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 41088 entries, 0 to 41087
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Id                         41088 non-null  int64
 1   Store                      41088 non-null  int64
 2   DayOfWeek                  41088 non-null  int64
 3   Date                       41088 non-null  datetime64[ns]
 4   Open                       41077 non-null  float64
 5   Promo                      41088 non-null  int64
 6   StateHoliday               41088 non-null  object
 7   SchoolHoliday              41088 non-null  int64
 8   StoreType                  41088 non-null  object
 9   Assortment                 41088 non-null  object
 10  CompetitionDistance        40992 non-null  float64
 11  CompetitionOpenSinceMonth  25872 non-null  float64
 12  CompetitionOpenSinceYear   25872 non-null  float64
 13  Promo2                     41088 non-null  int64
 14  Promo2SinceWeek            23856 non-null  float64
 15  Promo2SinceYear            23856 non-null  float64
 16  PromoInterval              23856 non-null  object
 17  Year                       41088 non-null  int64
 18  Month                      41088 non-null  int64
 19  weekDay                    41088 non-null  int64
 20  IsWeekday                  41088 non-null  int64
dtypes: datetime64[ns](1), float64(6), int64(10), object(4)
memory usage: 6.9+ MB

In [58]:
# Extract Quarter
train_merged_data['Quarter'] = train_merged_data['Date'].dt.quarter
test_merged_data['Quarter'] = test_merged_data['Date'].dt.quarter

In [59]:

train_merged_data['SalesPerCustomer'] = train_merged_data['Sales'] / train_merged_data['Customers']

In [60]:
# Extract features for the beginning, middle, and end of the month
train_merged_data['IsMonthStart'] = train_merged_data['Date'].dt.is_month_start.astype(int)
train_merged_data['IsMonthMiddle'] = ((train_merged_data['weekDay'] >= 10) & (train_merged_data['weekDay'] <= 20)).astype(int)
train_merged_data['IsMonthEnd'] = train_merged_data['Date'].dt.is_month_end.astype(int)

In [61]:
test_merged_data['IsMonthStart'] = test_merged_data['Date'].dt.is_month_start.astype(int)
test_merged_data['IsMonthMiddle'] = ((test_merged_data['weekDay'] >= 10) & (test_merged_data['weekDay'] <= 20)).astype(int)
test_merged_data['IsMonthEnd'] = test_merged_data['Date'].dt.is_month_end.astype(int)

In [62]:
train_merged_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1017209 entries, 0 to 1017208
Data columns (total 27 columns):
 #   Column                     Non-Null Count    Dtype
---  ------                     --------------    -----
 0   Store                      1017209 non-null  int64
 1   DayOfWeek                  1017209 non-null  int64
 2   Date                       1017209 non-null  datetime64[ns]
 3   Sales                      1017209 non-null  int64
 4   Customers                  1017209 non-null  int64
 5   Open                       1017209 non-null  int64
 6   Promo                      1017209 non-null  int64
 7   StateHoliday               1017209 non-null  object
 8   SchoolHoliday              1017209 non-null  int64
 9   StoreType                  1017209 non-null  object
 10  Assortment                 1017209 non-null  object
 11  CompetitionDistance        1014567 non-null  float64
 12  CompetitionOpenSinceMonth  693861 non-null   float64
 13  CompetitionOpenSinceYear   693861 non-null   float64
 14  Promo2                     1017209 non-null  int64
 15  Promo2SinceWeek            509178 non-null   float64
 16  Promo2SinceYear            509178 non-null   float64
 17  PromoInterval              509178 non-null   object
 18  Year                       1017209 non-null  int64
 19  Month                      1017209 non-null  int64
 20  weekDay                    1017209 non-null  int64
 21  IsWeekday                  1017209 non-null  int64
 22  Quarter                    1017209 non-null  int64
 23  SalesPerCustomer           844340 non-null   float64
 24  IsMonthStart               1017209 non-null  int64
 25  IsMonthMiddle              1017209 non-null  int64
 26  IsMonthEnd                 1017209 non-null  int64
dtypes: datetime64[ns](1), float64(6), int64(16), object(4)
memory usage: 217.3+ MB

In [63]:
test_merged_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 41088 entries, 0 to 41087
Data columns (total 25 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Id                         41088 non-null  int64
 1   Store                      41088 non-null  int64
 2   DayOfWeek                  41088 non-null  int64
 3   Date                       41088 non-null  datetime64[ns]
 4   Open                       41077 non-null  float64
 5   Promo                      41088 non-null  int64
 6   StateHoliday               41088 non-null  object
 7   SchoolHoliday              41088 non-null  int64
 8   StoreType                  41088 non-null  object
 9   Assortment                 41088 non-null  object
 10  CompetitionDistance        40992 non-null  float64
 11  CompetitionOpenSinceMonth  25872 non-null  float64
 12  CompetitionOpenSinceYear   25872 non-null  float64
 13  Promo2                     41088 non-null  int64
 14  Promo2SinceWeek            23856 non-null  float64
 15  Promo2SinceYear            23856 non-null  float64
 16  PromoInterval              23856 non-null  object
 17  Year                       41088 non-null  int64
 18  Month                      41088 non-null  int64
 19  weekDay                    41088 non-null  int64
 20  IsWeekday                  41088 non-null  int64
 21  Quarter                    41088 non-null  int64
 22  IsMonthStart               41088 non-null  int64
 23  IsMonthMiddle              41088 non-null  int64
 24  IsMonthEnd                 41088 non-null  int64
dtypes: datetime64[ns](1), float64(6), int64(14), object(4)
memory usage: 8.2+ MB

In [64]:
test_merged_data

,Id,Store,DayOfWeek,Date,Open,Promo,StateHoliday,SchoolHoliday,StoreType,Assortment,...,Promo2SinceYear,PromoInterval,Year,Month,weekDay,IsWeekday,Quarter,IsMonthStart,IsMonthMiddle,IsMonthEnd
0,1,1,4,2015-09-17,1.0,1,0,0,c,a,...,NaN,NaN,2015,9,17,1,3,0,1,0
1,2,3,4,2015-09-17,1.0,1,0,0,a,a,...,2011.0,"Jan,Apr,Jul,Oct",2015,9,17,1,3,0,1,0
2,3,7,4,2015-09-17,1.0,1,0,0,a,c,...,NaN,NaN,2015,9,17,1,3,0,1,0
3,4,8,4,2015-09-17,1.0,1,0,0,a,a,...,NaN,NaN,2015,9,17,1,3,0,1,0
4,5,9,4,2015-09-17,1.0,1,0,0,a,c,...,NaN,NaN,2015,9,17,1,3,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41083,41084,1111,6,2015-08-01,1.0,0,0,0,a,a,...,2013.0,"Jan,Apr,Jul,Oct",2015,8,1,0,3,1,0,0
41084,41085,1112,6,2015-08-01,1.0,0,0,0,c,c,...,NaN,NaN,2015,8,1,0,3,1,0,0
41085,41086,1113,6,2015-08-01,1.0,0,0,0,a,c,...,NaN,NaN,2015,8,1,0,3,1,0,0
41086,41087,1114,6,2015-08-01,1.0,0,0,0,a,c,...,NaN,NaN,2015,8,1,0,3,1,0,0
41087,41088,1115,6,2015-08-01,1.0,0,0,1,d,c,...,2012.0,"Mar,Jun,Sept,Dec",2015,8,1,0,3,1,0,0

In [65]:
train_merged_data

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday,StoreType,...,PromoInterval,Year,Month,weekDay,IsWeekday,Quarter,SalesPerCustomer,IsMonthStart,IsMonthMiddle,IsMonthEnd
0,1,5,2015-07-31,5263,555,1,1,0,1,c,...,NaN,2015,7,31,0,3,9.482883,0,0,1
1,2,5,2015-07-31,6064,625,1,1,0,1,a,...,"Jan,Apr,Jul,Oct",2015,7,31,0,3,9.702400,0,0,1
2,3,5,2015-07-31,8314,821,1,1,0,1,a,...,"Jan,Apr,Jul,Oct",2015,7,31,0,3,10.126675,0,0,1
3,4,5,2015-07-31,13995,1498,1,1,0,1,c,...,NaN,2015,7,31,0,3,9.342457,0,0,1
4,5,5,2015-07-31,4822,559,1,1,0,1,a,...,NaN,2015,7,31,0,3,8.626118,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1017204,1111,2,2013-01-01,0,0,0,0,a,1,a,...,"Jan,Apr,Jul,Oct",2013,1,1,1,1,NaN,1,0,0
1017205,1112,2,2013-01-01,0,0,0,0,a,1,c,...,NaN,2013,1,1,1,1,NaN,1,0,0
1017206,1113,2,2013-01-01,0,0,0,0,a,1,a,...,NaN,2013,1,1,1,1,NaN,1,0,0
1017207,1114,2,2013-01-01,0,0,0,0,a,1,a,...,NaN,2013,1,1,1,1,NaN,1,0,0
1017208,1115,2,2013-01-01,0,0,0,0,a,1,d,...,"Mar,Jun,Sept,Dec",2013,1,1,1,1,NaN,1,0,0

In [66]:
train_merged_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1017209 entries, 0 to 1017208
Data columns (total 27 columns):
 #   Column                     Non-Null Count    Dtype
---  ------                     --------------    -----
 0   Store                      1017209 non-null  int64
 1   DayOfWeek                  1017209 non-null  int64
 2   Date                       1017209 non-null  datetime64[ns]
 3   Sales                      1017209 non-null  int64
 4   Customers                  1017209 non-null  int64
 5   Open                       1017209 non-null  int64
 6   Promo                      1017209 non-null  int64
 7   StateHoliday               1017209 non-null  object
 8   SchoolHoliday              1017209 non-null  int64
 9   StoreType                  1017209 non-null  object
 10  Assortment                 1017209 non-null  object
 11  CompetitionDistance        1014567 non-null  float64
 12  CompetitionOpenSinceMonth  693861 non-null   float64
 13  CompetitionOpenSinceYear   693861 non-null   float64
 14  Promo2                     1017209 non-null  int64
 15  Promo2SinceWeek            509178 non-null   float64
 16  Promo2SinceYear            509178 non-null   float64
 17  PromoInterval              509178 non-null   object
 18  Year                       1017209 non-null  int64
 19  Month                      1017209 non-null  int64
 20  weekDay                    1017209 non-null  int64
 21  IsWeekday                  1017209 non-null  int64
 22  Quarter                    1017209 non-null  int64
 23  SalesPerCustomer           844340 non-null   float64
 24  IsMonthStart               1017209 non-null  int64
 25  IsMonthMiddle              1017209 non-null  int64
 26  IsMonthEnd                 1017209 non-null  int64
dtypes: datetime64[ns](1), float64(6), int64(16), object(4)
memory usage: 217.3+ MB

In [67]:
train_merged_data.columns

Index(['Store', 'DayOfWeek', 'Date', 'Sales', 'Customers', 'Open', 'Promo',
       'StateHoliday', 'SchoolHoliday', 'StoreType', 'Assortment',
       'CompetitionDistance', 'CompetitionOpenSinceMonth',
       'CompetitionOpenSinceYear', 'Promo2', 'Promo2SinceWeek',
       'Promo2SinceYear', 'PromoInterval', 'Year', 'Month', 'weekDay',
       'IsWeekday', 'Quarter', 'SalesPerCustomer', 'IsMonthStart',
       'IsMonthMiddle', 'IsMonthEnd'],
      dtype='object')

In [68]:
train_merged_data['StateHoliday'] = train_merged_data['StateHoliday'].astype(str)

In [69]:
categorical_columns_test = [var for var in test_merged_data.columns if test_merged_data[var].dtypes=='O']
numerical_columns_test = [var for var in test_merged_data.columns if test_merged_data[var].dtypes!='O']

In [70]:
categorical_columns_test

['StateHoliday', 'StoreType', 'Assortment', 'PromoInterval']

In [71]:
numerical_columns_test

['Id',
 'Store',
 'DayOfWeek',
 'Date',
 'Open',
 'Promo',
 'SchoolHoliday',
 'CompetitionDistance',
 'CompetitionOpenSinceMonth',
 'CompetitionOpenSinceYear',
 'Promo2',
 'Promo2SinceWeek',
 'Promo2SinceYear',
 'Year',
 'Month',
 'weekDay',
 'IsWeekday',
 'Quarter',
 'IsMonthStart',
 'IsMonthMiddle',
 'IsMonthEnd']

In [72]:
categorical_columns_train = [var for var in train_merged_data.columns if train_merged_data[var].dtypes=='O']
numerical_columns_train = [var for var in train_merged_data.columns if train_merged_data[var].dtypes!='O']

In [73]:
categorical_columns_train

['StateHoliday', 'StoreType', 'Assortment', 'PromoInterval']

In [74]:
numerical_columns_train

['Store',
 'DayOfWeek',
 'Date',
 'Sales',
 'Customers',
 'Open',
 'Promo',
 'SchoolHoliday',
 'CompetitionDistance',
 'CompetitionOpenSinceMonth',
 'CompetitionOpenSinceYear',
 'Promo2',
 'Promo2SinceWeek',
 'Promo2SinceYear',
 'Year',
 'Month',
 'weekDay',
 'IsWeekday',
 'Quarter',
 'SalesPerCustomer',
 'IsMonthStart',
 'IsMonthMiddle',
 'IsMonthEnd']

In [75]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
train_merged_data['StoreType'] = label_encoder.fit_transform(train_merged_data['StoreType'])
train_merged_data['StateHoliday'] = label_encoder.fit_transform(train_merged_data['StateHoliday'])
train_merged_data['Assortment'] = label_encoder.fit_transform(train_merged_data['Assortment'])
train_merged_data['PromoInterval'] = label_encoder.fit_transform(train_merged_data['PromoInterval'])

In [76]:
train_merged_data['StateHoliday'] = train_merged_data['StateHoliday'].astype(str)

In [77]:
train_merged_data['StateHoliday'].unique()

array(['0', '1', '2', '3'], dtype=object)

In [78]:
test_merged_data['StateHoliday'] = label_encoder.fit_transform(test_merged_data['StateHoliday'])
test_merged_data['StoreType'] = label_encoder.fit_transform(test_merged_data['StoreType'])
test_merged_data['StateHoliday'] = label_encoder.fit_transform(test_merged_data['StateHoliday'])
test_merged_data['Assortment'] = label_encoder.fit_transform(test_merged_data['Assortment'])
test_merged_data['PromoInterval'] = label_encoder.fit_transform(test_merged_data['PromoInterval'])

In [79]:
test_merged_data['StoreType'] =label_encoder.fit_transform(test_merged_data['StoreType'])

In [80]:
test_merged_data['StateHoliday'].unique()

array([0, 1])

In [81]:
test_merged_data.columns

Index(['Id', 'Store', 'DayOfWeek', 'Date', 'Open', 'Promo', 'StateHoliday',
       'SchoolHoliday', 'StoreType', 'Assortment', 'CompetitionDistance',
       'CompetitionOpenSinceMonth', 'CompetitionOpenSinceYear', 'Promo2',
       'Promo2SinceWeek', 'Promo2SinceYear', 'PromoInterval', 'Year', 'Month',
       'weekDay', 'IsWeekday', 'Quarter', 'IsMonthStart', 'IsMonthMiddle',
       'IsMonthEnd'],
      dtype='object')

In [82]:
train_merged_data['StateHoliday'] = train_merged_data['StateHoliday'].astype(int)

In [83]:
test_merged_data['StateHoliday'] = test_merged_data['StateHoliday'].astype(int)

In [84]:
test_merged_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 41088 entries, 0 to 41087
Data columns (total 25 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Id                         41088 non-null  int64
 1   Store                      41088 non-null  int64
 2   DayOfWeek                  41088 non-null  int64
 3   Date                       41088 non-null  datetime64[ns]
 4   Open                       41077 non-null  float64
 5   Promo                      41088 non-null  int64
 6   StateHoliday               41088 non-null  int64
 7   SchoolHoliday              41088 non-null  int64
 8   StoreType                  41088 non-null  int64
 9   Assortment                 41088 non-null  int64
 10  CompetitionDistance        40992 non-null  float64
 11  CompetitionOpenSinceMonth  25872 non-null  float64
 12  CompetitionOpenSinceYear   25872 non-null  float64
 13  Promo2                     41088 non-null  int64
 14  Promo2SinceWeek            23856 non-null  float64
 15  Promo2SinceYear            23856 non-null  float64
 16  PromoInterval              41088 non-null  int64
 17  Year                       41088 non-null  int64
 18  Month                      41088 non-null  int64
 19  weekDay                    41088 non-null  int64
 20  IsWeekday                  41088 non-null  int64
 21  Quarter                    41088 non-null  int64
 22  IsMonthStart               41088 non-null  int64
 23  IsMonthMiddle              41088 non-null  int64
 24  IsMonthEnd                 41088 non-null  int64
dtypes: datetime64[ns](1), float64(6), int64(18)
memory usage: 8.2 MB

In [85]:
train_merged_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1017209 entries, 0 to 1017208
Data columns (total 27 columns):
 #   Column                     Non-Null Count    Dtype
---  ------                     --------------    -----
 0   Store                      1017209 non-null  int64
 1   DayOfWeek                  1017209 non-null  int64
 2   Date                       1017209 non-null  datetime64[ns]
 3   Sales                      1017209 non-null  int64
 4   Customers                  1017209 non-null  int64
 5   Open                       1017209 non-null  int64
 6   Promo                      1017209 non-null  int64
 7   StateHoliday               1017209 non-null  int64
 8   SchoolHoliday              1017209 non-null  int64
 9   StoreType                  1017209 non-null  int64
 10  Assortment                 1017209 non-null  int64
 11  CompetitionDistance        1014567 non-null  float64
 12  CompetitionOpenSinceMonth  693861 non-null   float64
 13  CompetitionOpenSinceYear   693861 non-null   float64
 14  Promo2                     1017209 non-null  int64
 15  Promo2SinceWeek            509178 non-null   float64
 16  Promo2SinceYear            509178 non-null   float64
 17  PromoInterval              1017209 non-null  int64
 18  Year                       1017209 non-null  int64
 19  Month                      1017209 non-null  int64
 20  weekDay                    1017209 non-null  int64
 21  IsWeekday                  1017209 non-null  int64
 22  Quarter                    1017209 non-null  int64
 23  SalesPerCustomer           844340 non-null   float64
 24  IsMonthStart               1017209 non-null  int64
 25  IsMonthMiddle              1017209 non-null  int64
 26  IsMonthEnd                 1017209 non-null  int64
dtypes: datetime64[ns](1), float64(6), int64(20)
memory usage: 217.3 MB

In [86]:
test_merged_data.shape

(41088, 25)

In [87]:
train_merged_data.shape

(1017209, 27)

In [88]:
train_merged_data.columns

Index(['Store', 'DayOfWeek', 'Date', 'Sales', 'Customers', 'Open', 'Promo',
       'StateHoliday', 'SchoolHoliday', 'StoreType', 'Assortment',
       'CompetitionDistance', 'CompetitionOpenSinceMonth',
       'CompetitionOpenSinceYear', 'Promo2', 'Promo2SinceWeek',
       'Promo2SinceYear', 'PromoInterval', 'Year', 'Month', 'weekDay',
       'IsWeekday', 'Quarter', 'SalesPerCustomer', 'IsMonthStart',
       'IsMonthMiddle', 'IsMonthEnd'],
      dtype='object')

In [89]:
test_merged_data.columns

Index(['Id', 'Store', 'DayOfWeek', 'Date', 'Open', 'Promo', 'StateHoliday',
       'SchoolHoliday', 'StoreType', 'Assortment', 'CompetitionDistance',
       'CompetitionOpenSinceMonth', 'CompetitionOpenSinceYear', 'Promo2',
       'Promo2SinceWeek', 'Promo2SinceYear', 'PromoInterval', 'Year', 'Month',
       'weekDay', 'IsWeekday', 'Quarter', 'IsMonthStart', 'IsMonthMiddle',
       'IsMonthEnd'],
      dtype='object')

In [90]:
# Drop columns from train_data_merged
train_merged_data.drop(columns=['Sales', 'Customers'], inplace=True)

# Drop columns from test_data_merged
test_merged_data.drop(columns=['Id'], inplace=True)

In [91]:
train_merged_data.set_index('Date', inplace=True)
train_merged_data.sort_index(inplace=True)

In [92]:
test_merged_data.set_index('Date', inplace=True)
test_merged_data.sort_index(inplace=True)

In [93]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

# Initialize the StandardScaler
scaler = StandardScaler()

In [94]:

from sklearn.preprocessing import MinMaxScaler
scaler= MinMaxScaler()

In [95]:
# Apply Min-Max scaling to train_merged_data
train_merged_data_scaled = scaler.fit_transform(train_merged_data)

In [96]:
# Apply Min-Max scaling to test_merged_data
test_merged_data_scaled = scaler.fit_transform(test_merged_data)

2.2 Building models with sklearn pipelines
At this point, all our features are numeric. Since our problem is a regression problem, you
can narrow down the list of algorithms you can use for modelling.
A reasonable starting point will be to use any of the tree based algorithms. Random
forests Regressor will make for a good start.
Also, for the sake of this challenge, work with sklearn pipelines. This makes modeling
modular and more reproducible. Working with pipelines will also significantly reduce
your workload when you are moving your setup into files for the next part of the
challenge. Extra marks will be awarded for doing this.

2.3 Choose a loss function

Loss functions indicate how well our model is performing. This means that the loss
functions affect the overall output of sales prediction.
Different loss functions have different use cases.

In this challenge, youâ€™re allowed to choose your own loss function. you need to defend
the loss function you choose for this challenge. Feel free to be creative with your choice.
You might want to use loss functions that are easily interpretable.

In [97]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.compose import ColumnTransformer

In [98]:
train_merged_data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1017209 entries, 2013-01-01 to 2015-07-31
Data columns (total 24 columns):
 #   Column                     Non-Null Count    Dtype
---  ------                     --------------    -----
 0   Store                      1017209 non-null  int64
 1   DayOfWeek                  1017209 non-null  int64
 2   Open                       1017209 non-null  int64
 3   Promo                      1017209 non-null  int64
 4   StateHoliday               1017209 non-null  int64
 5   SchoolHoliday              1017209 non-null  int64
 6   StoreType                  1017209 non-null  int64
 7   Assortment                 1017209 non-null  int64
 8   CompetitionDistance        1014567 non-null  float64
 9   CompetitionOpenSinceMonth  693861 non-null   float64
 10  CompetitionOpenSinceYear   693861 non-null   float64
 11  Promo2                     1017209 non-null  int64
 12  Promo2SinceWeek            509178 non-null   float64
 13  Promo2SinceYear            509178 non-null   float64
 14  PromoInterval              1017209 non-null  int64
 15  Year                       1017209 non-null  int64
 16  Month                      1017209 non-null  int64
 17  weekDay                    1017209 non-null  int64
 18  IsWeekday                  1017209 non-null  int64
 19  Quarter                    1017209 non-null  int64
 20  SalesPerCustomer           844340 non-null   float64
 21  IsMonthStart               1017209 non-null  int64
 22  IsMonthMiddle              1017209 non-null  int64
 23  IsMonthEnd                 1017209 non-null  int64
dtypes: float64(6), int64(18)
memory usage: 194.0 MB

In [99]:
train_merged_data.columns

Index(['Store', 'DayOfWeek', 'Open', 'Promo', 'StateHoliday', 'SchoolHoliday',
       'StoreType', 'Assortment', 'CompetitionDistance',
       'CompetitionOpenSinceMonth', 'CompetitionOpenSinceYear', 'Promo2',
       'Promo2SinceWeek', 'Promo2SinceYear', 'PromoInterval', 'Year', 'Month',
       'weekDay', 'IsWeekday', 'Quarter', 'SalesPerCustomer', 'IsMonthStart',
       'IsMonthMiddle', 'IsMonthEnd'],
      dtype='object')

In [100]:
# Define features and target variable
X = train_merged_data[['Store', 'DayOfWeek', 'Open', 'Promo', 'StateHoliday', 'SchoolHoliday',
       'StoreType', 'Assortment', 'CompetitionDistance',
       'CompetitionOpenSinceMonth', 'CompetitionOpenSinceYear', 'Promo2',
       'Promo2SinceWeek', 'Promo2SinceYear', 'PromoInterval', 'Year', 'Month',
       'weekDay', 'IsWeekday', 'Quarter', 'IsMonthStart',
       'IsMonthMiddle', 'IsMonthEnd']]
y = train_merged_data['SalesPerCustomer']

In [101]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [102]:
X_train

,Store,DayOfWeek,Open,Promo,StateHoliday,SchoolHoliday,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,...,Promo2SinceYear,PromoInterval,Year,Month,weekDay,IsWeekday,Quarter,IsMonthStart,IsMonthMiddle,IsMonthEnd
Date,,,,,,,,,,,,,,,,,,,,,
2014-01-10,895,5,1,1,0,0,0,2,4150.0,NaN,...,NaN,3,2014,1,10,0,1,0,1,0
2014-08-24,509,7,0,0,0,1,0,0,4740.0,7.0,...,2009.0,1,2014,8,24,0,3,0,0,0
2014-11-18,440,2,1,0,0,0,3,0,3900.0,4.0,...,2009.0,0,2014,11,18,1,4,0,1,0
2013-04-09,37,2,1,1,0,0,2,0,4230.0,12.0,...,NaN,3,2013,4,9,1,2,0,0,0
2014-01-14,706,2,1,0,0,0,3,0,7830.0,9.0,...,2014.0,2,2014,1,14,1,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2013-08-21,159,3,1,0,0,1,3,0,8530.0,3.0,...,NaN,3,2013,8,21,1,3,0,0,0
2013-11-25,332,1,1,0,0,0,0,0,1840.0,3.0,...,NaN,3,2013,11,25,1,4,0,0,0
2013-04-29,17,1,1,1,0,0,0,0,50.0,12.0,...,2010.0,1,2013,4,29,1,2,0,0,0
2014-09-05,996,5,1,1,0,0,2,0,2870.0,7.0,...,2010.0,1,2014,9,5,0,3,0,0,0
2013-04-20,234,6,1,0,0,0,3,0,4370.0,NaN,...,NaN,3,2013,4,20,0,2,0,1,0

In [103]:

X_test.shape

(203442, 23)

In [104]:
X_train.shape

(813767, 23)

In [105]:
y_test.shape

(203442,)

In [106]:
y_train.shape

(813767,)

In [107]:
# Making separate lists for categorical and numerical columns
categorical_cols, numerical_cols = [], []

for i in train_merged_data.columns:
    print("The datatype for {} is {}".format(i,train_merged_data[i].dtypes))
    # check if the datatype is object or not
    if train_merged_data[i].dtypes == "object":
        # if the datatype is object : --> fillna with mode of that column
        mode_value = train_merged_data[i].mode()[0]
        train_merged_data[i].fillna(mode_value, inplace = True)
    elif train_merged_data[i].dtypes != "object":
        # if data[i].dtypes == "bool":
        #     data[i].fillna(0, inplace = True)
        # else:
        # else if the datatype is numerical : --> fillna with mean of that column
        mean_value = train_merged_data[i].mean()
        train_merged_data[i].fillna(mean_value, inplace = True)

The datatype for Store is int64
The datatype for DayOfWeek is int64
The datatype for Open is int64
The datatype for Promo is int64
The datatype for StateHoliday is int64
The datatype for SchoolHoliday is int64
The datatype for StoreType is int64
The datatype for Assortment is int64
The datatype for CompetitionDistance is float64
The datatype for CompetitionOpenSinceMonth is float64
The datatype for CompetitionOpenSinceYear is float64
The datatype for Promo2 is int64
The datatype for Promo2SinceWeek is float64
The datatype for Promo2SinceYear is float64
The datatype for PromoInterval is int64
The datatype for Year is int64
The datatype for Month is int64
The datatype for weekDay is int64
The datatype for IsWeekday is int64
The datatype for Quarter is int64
The datatype for SalesPerCustomer is float64
The datatype for IsMonthStart is int64
The datatype for IsMonthMiddle is int64
The datatype for IsMonthEnd is int64

In [108]:
# Making separate lists for categorical and numerical columns
categorical_cols, numerical_cols = [], []

for i in test_merged_data.columns:
    print("The datatype for {} is {}".format(i,test_merged_data[i].dtypes))
    # check if the datatype is object or not
    if test_merged_data[i].dtypes == "object":
        # if the datatype is object : --> fillna with mode of that column
        mode_value = test_merged_data[i].mode()[0]
        test_merged_data[i].fillna(mode_value, inplace = True)
    elif test_merged_data[i].dtypes != "object":
        mean_value = test_merged_data[i].mean()
        test_merged_data[i].fillna(mean_value, inplace = True)

The datatype for Store is int64
The datatype for DayOfWeek is int64
The datatype for Open is float64
The datatype for Promo is int64
The datatype for StateHoliday is int64
The datatype for SchoolHoliday is int64
The datatype for StoreType is int64
The datatype for Assortment is int64
The datatype for CompetitionDistance is float64
The datatype for CompetitionOpenSinceMonth is float64
The datatype for CompetitionOpenSinceYear is float64
The datatype for Promo2 is int64
The datatype for Promo2SinceWeek is float64
The datatype for Promo2SinceYear is float64
The datatype for PromoInterval is int64
The datatype for Year is int64
The datatype for Month is int64
The datatype for weekDay is int64
The datatype for IsWeekday is int64
The datatype for Quarter is int64
The datatype for IsMonthStart is int64
The datatype for IsMonthMiddle is int64
The datatype for IsMonthEnd is int64

In [109]:
train_merged_data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1017209 entries, 2013-01-01 to 2015-07-31
Data columns (total 24 columns):
 #   Column                     Non-Null Count    Dtype
---  ------                     --------------    -----
 0   Store                      1017209 non-null  int64
 1   DayOfWeek                  1017209 non-null  int64
 2   Open                       1017209 non-null  int64
 3   Promo                      1017209 non-null  int64
 4   StateHoliday               1017209 non-null  int64
 5   SchoolHoliday              1017209 non-null  int64
 6   StoreType                  1017209 non-null  int64
 7   Assortment                 1017209 non-null  int64
 8   CompetitionDistance        1017209 non-null  float64
 9   CompetitionOpenSinceMonth  1017209 non-null  float64
 10  CompetitionOpenSinceYear   1017209 non-null  float64
 11  Promo2                     1017209 non-null  int64
 12  Promo2SinceWeek            1017209 non-null  float64
 13  Promo2SinceYear            1017209 non-null  float64
 14  PromoInterval              1017209 non-null  int64
 15  Year                       1017209 non-null  int64
 16  Month                      1017209 non-null  int64
 17  weekDay                    1017209 non-null  int64
 18  IsWeekday                  1017209 non-null  int64
 19  Quarter                    1017209 non-null  int64
 20  SalesPerCustomer           1017209 non-null  float64
 21  IsMonthStart               1017209 non-null  int64
 22  IsMonthMiddle              1017209 non-null  int64
 23  IsMonthEnd                 1017209 non-null  int64
dtypes: float64(6), int64(18)
memory usage: 194.0 MB

In [110]:
test_merged_data.info

<bound method DataFrame.info of             Store  DayOfWeek  Open  Promo  StateHoliday  SchoolHoliday  \
Date
2015-08-01   1115          6   1.0      0             0              1
2015-08-01    378          6   1.0      0             0              0
2015-08-01    377          6   1.0      0             0              0
2015-08-01    373          6   1.0      0             0              0
2015-08-01    372          6   1.0      0             0              0
...           ...        ...   ...    ...           ...            ...
2015-09-17    732          4   1.0      1             0              0
2015-09-17    731          4   1.0      1             0              0
2015-09-17    729          4   1.0      1             0              0
2015-09-17    727          4   1.0      1             0              0
2015-09-17      1          4   1.0      1             0              0

            StoreType  Assortment  CompetitionDistance  \
Date
2015-08-01          3           2               5350.0
2015-08-01          0           2               2140.0
2015-08-01          0           2                100.0
2015-08-01          3           2              11120.0
2015-08-01          3           2               4880.0
...               ...         ...                  ...
2015-09-17          0           2              35280.0
2015-09-17          0           0              15270.0
2015-09-17          2           2               8980.0
2015-09-17          0           0               2050.0
2015-09-17          2           0               1270.0

            CompetitionOpenSinceMonth  ...  Promo2SinceYear  PromoInterval  \
Date                                   ...
2015-08-01                    7.03525  ...      2012.000000              2
2015-08-01                    8.00000  ...      2011.820926              3
2015-08-01                    6.00000  ...      2010.000000              0
2015-08-01                    7.03525  ...      2012.000000              1
2015-08-01                    8.00000  ...      2014.000000              1
...                               ...  ...              ...            ...
2015-09-17                    7.03525  ...      2011.820926              3
2015-09-17                    7.03525  ...      2014.000000              1
2015-09-17                    6.00000  ...      2011.820926              3
2015-09-17                    3.00000  ...      2011.820926              3
2015-09-17                    9.00000  ...      2011.820926              3

            Year  Month  weekDay  IsWeekday  Quarter  IsMonthStart  \
Date
2015-08-01  2015      8        1          0        3             1
2015-08-01  2015      8        1          0        3             1
2015-08-01  2015      8        1          0        3             1
2015-08-01  2015      8        1          0        3             1
2015-08-01  2015      8        1          0        3             1
...          ...    ...      ...        ...      ...           ...
2015-09-17  2015      9       17          1        3             0
2015-09-17  2015      9       17          1        3             0
2015-09-17  2015      9       17          1        3             0
2015-09-17  2015      9       17          1        3             0
2015-09-17  2015      9       17          1        3             0

            IsMonthMiddle  IsMonthEnd
Date
2015-08-01              0           0
2015-08-01              0           0
2015-08-01              0           0
2015-08-01              0           0
2015-08-01              0           0
...                   ...         ...
2015-09-17              1           0
2015-09-17              1           0
2015-09-17              1           0
2015-09-17              1           0
2015-09-17              1           0

[41088 rows x 23 columns]>

In [111]:
test_merged_data.columns

Index(['Store', 'DayOfWeek', 'Open', 'Promo', 'StateHoliday', 'SchoolHoliday',
       'StoreType', 'Assortment', 'CompetitionDistance',
       'CompetitionOpenSinceMonth', 'CompetitionOpenSinceYear', 'Promo2',
       'Promo2SinceWeek', 'Promo2SinceYear', 'PromoInterval', 'Year', 'Month',
       'weekDay', 'IsWeekday', 'Quarter', 'IsMonthStart', 'IsMonthMiddle',
       'IsMonthEnd'],
      dtype='object')

In [112]:
train_merged_data.columns

Index(['Store', 'DayOfWeek', 'Open', 'Promo', 'StateHoliday', 'SchoolHoliday',
       'StoreType', 'Assortment', 'CompetitionDistance',
       'CompetitionOpenSinceMonth', 'CompetitionOpenSinceYear', 'Promo2',
       'Promo2SinceWeek', 'Promo2SinceYear', 'PromoInterval', 'Year', 'Month',
       'weekDay', 'IsWeekday', 'Quarter', 'SalesPerCustomer', 'IsMonthStart',
       'IsMonthMiddle', 'IsMonthEnd'],
      dtype='object')

In [113]:
X =train_merged_data[['Store', 'DayOfWeek', 'Open', 'Promo', 'StateHoliday', 'SchoolHoliday',
       'StoreType', 'Assortment', 'CompetitionDistance',
       'CompetitionOpenSinceMonth', 'CompetitionOpenSinceYear', 'Promo2',
       'Promo2SinceWeek', 'Promo2SinceYear', 'PromoInterval', 'Year', 'Month',
       'weekDay', 'IsWeekday', 'Quarter', 'IsMonthStart', 'IsMonthMiddle',
       'IsMonthEnd']]
y = train_merged_data['SalesPerCustomer']

In [114]:
X_train, X_test, y_train, y_test = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

In [115]:
import numpy as np
# Remove rows with missing values
x_train = train_merged_data.dropna(subset=X.columns)

In [116]:
X_train = train_merged_data.dropna(subset=X.columns)
y_train = X_train['SalesPerCustomer']
X_train = X_train.drop(columns=['SalesPerCustomer'])

In [117]:
# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

In [118]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')
regressor = LinearRegression()

In [119]:
pipeline = Pipeline([
    ('imputer', StandardScaler()),  # Feature scaling (optional)
    ('refressor', regressor)])

In [120]:
# Fit the pipeline to the training data
pipeline.fit(X_train, y_train)

Pipeline(steps=[('imputer', StandardScaler()),
                ('refressor', LinearRegression())])

In [121]:
# Make predictions on the test data
y_pred = pipeline.predict(X_test)

In [122]:
mse = mean_squared_error(y_test, y_pred)
print(f'Mean Squared Error: {mse}')

Mean Squared Error: 2.7168604478654887

In [123]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [124]:
from sklearn.tree import DecisionTreeRegressor
# Decision Tree Regressor
decision_tree = DecisionTreeRegressor(random_state=42)
decision_tree.fit(X_train, y_train)
y_pred_decision_tree = decision_tree.predict(X_test)
mse_decision_tree = mean_squared_error(y_test, y_pred_decision_tree)
print(f'Decision Tree MSE: {mse_decision_tree}')

Decision Tree MSE: 0.5016668223334577

In [125]:
from sklearn.ensemble import RandomForestRegressor
random_forest = RandomForestRegressor(random_state=42)

In [126]:
random_forest.fit(X_train, y_train)
y_pred_random_forest = random_forest.predict(X_test)
mse_random_forest = mean_squared_error(y_test, y_pred_random_forest)
print(f'Random Forest MSE: {mse_random_forest}')

Random Forest MSE: 0.26002200511040763

In [127]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

knn_regressor = KNeighborsRegressor(n_neighbors=5)

In [128]:
# Create a KNN regressor
knn_regressor = KNeighborsRegressor(n_neighbors=5)
print('X_Train shape:',X_train.shape)
print('X_Test shape:',X_test.shape)
print('Y_Train shape:',y_train.shape)
print('Y_Test shape:',y_test.shape)

# Train the model
knn_regressor.fit(X_train, y_train)

# Predict on the test set
y_pred = knn_regressor.predict(X_test)

# Calculate Mean Squared Error
knn_mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", knn_mse)

X_Train shape: (813767, 23)
X_Test shape: (203442, 23)
Y_Train shape: (813767,)
Y_Test shape: (203442,)
Mean Squared Error: 0.7423308567798999

In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)  # Output layer for regression
])

model.compile(optimizer='adam', loss='mean_squared_error')
history = model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2, verbose=2)
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
print(f'Mean Squared Error: {mse}')

Epoch 1/10
20345/20345 - 42s - loss: 1.8188 - val_loss: 1.2936 - 42s/epoch - 2ms/step
Epoch 2/10
20345/20345 - 37s - loss: 1.1508 - val_loss: 0.9747 - 37s/epoch - 2ms/step
Epoch 3/10
20345/20345 - 40s - loss: 0.9299 - val_loss: 0.8513 - 40s/epoch - 2ms/step
Epoch 4/10
20345/20345 - 48s - loss: 0.7850 - val_loss: 0.6875 - 48s/epoch - 2ms/step
Epoch 5/10
20345/20345 - 41s - loss: 0.6965 - val_loss: 0.6311 - 41s/epoch - 2ms/step
Epoch 6/10
20345/20345 - 47s - loss: 0.6386 - val_loss: 0.5790 - 47s/epoch - 2ms/step
Epoch 7/10
20345/20345 - 39s - loss: 0.5997 - val_loss: 0.5280 - 39s/epoch - 2ms/step
Epoch 8/10
20345/20345 - 42s - loss: 0.5710 - val_loss: 0.5274 - 42s/epoch - 2ms/step
Epoch 9/10
20345/20345 - 42s - loss: 0.5519 - val_loss: 0.5514 - 42s/epoch - 2ms/step
Epoch 10/10

In [ ]:
train_data_merged.to_csv("train_df.csv")

In [ ]:
test_data_merged.to_csv("test_df.csv")